import Keycloak,{type KeycloakTokenParsed} from 'keycloak-js'
import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from 'react'
import type {PropsWithChildren} from 'react'
import {runtimeConfig} from '../config'
import {setTokenSupplier} from '../api/client'
type AuthState={ready:boolean;authenticated:boolean;displayName:string;email:string;roles:string[];isAdmin:boolean;login:()=>Promise<void>;logout:()=>Promise<void>}
const AuthContext=createContext<AuthState|undefined>(undefined)
const rolesOf=(token?:KeycloakTokenParsed)=>{const realm=token?.realm_access as {roles?:string[]}|undefined;const client=(token?.resource_access as Record<string,{roles?:string[]}>|undefined)?.[runtimeConfig.keycloakClientId];return [...new Set([...(realm?.roles??[]),...(client?.roles??[])])]}
export function AuthProvider({children}:PropsWithChildren){const ref=useRef<Keycloak|null>(null);const [ready,setReady]=useState(false);const [authenticated,setAuthenticated]=useState(false);const [,rev]=useState(0);useEffect(()=>{let cancelled=false;const kc=new Keycloak({url:runtimeConfig.keycloakUrl,realm:runtimeConfig.keycloakRealm,clientId:runtimeConfig.keycloakClientId});ref.current=kc;const refresh=async()=>{if(!kc.authenticated)return undefined;try{await kc.updateToken(30)}catch{await kc.login({redirectUri:window.location.href})}return kc.token};setTokenSupplier(refresh);kc.onTokenExpired=()=>{void refresh()};kc.onAuthRefreshSuccess=()=>rev(n=>n+1);kc.onAuthLogout=()=>setAuthenticated(false);void kc.init({onLoad:'login-required',pkceMethod:'S256',checkLoginIframe:false,redirectUri:window.location.href}).then(ok=>{if(!cancelled){setAuthenticated(ok);setReady(true);rev(n=>n+1)}}).catch(()=>{if(!cancelled)setReady(true)});return()=>{cancelled=true;setTokenSupplier(async()=>undefined)}},[]);const login=useCallback(async()=>{await ref.current?.login({redirectUri:window.location.href})},[]);const logout=useCallback(async()=>{await ref.current?.logout({redirectUri:`${window.location.origin}/`})},[]);const token=ref.current?.tokenParsed;const roles=rolesOf(token);const value=useMemo<AuthState>(()=>({ready,authenticated,displayName:String(token?.name??token?.preferred_username??'SceneScape user'),email:String(token?.email??''),roles,isAdmin:roles.includes('scenescape-admin'),login,logout}),[ready,authenticated,token,roles.join('|'),login,logout]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const v=useContext(AuthContext);if(!v)throw new Error('useAuth must be used inside AuthProvider');return v}
