{{- if gt (int .Values.worker.replicas) 1 }}
{{- $name := include "native.name" . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "{{ $name }}-worker"
{{- end }}
