// SPDX-FileCopyrightText: (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useRef, useState } from 'react'
import { apiBlob, apiFetch } from '../api/client'

type Entry={name:string;path:string;type:'directory'|'file'|'symlink';size:number|null}
type Listing={path:string;entries:Entry[]}
type DirectoryFile=File&{webkitRelativePath?:string}

const parent=(path:string)=>path.split('/').filter(Boolean).slice(0,-1).join('/')
const size=(value:number|null)=>value==null?'—':value<1024?String(value)+' B':(value/1024/1024).toFixed(2)+' MB'

export default function ModelLibrary({isAdmin}:{isAdmin:boolean}){
  const[path,setPath]=useState('');const[entries,setEntries]=useState<Entry[]>([]);const[configs,setConfigs]=useState<string[]>([])
  const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const filesRef=useRef<HTMLInputElement|null>(null);const folderRef=useRef<HTMLInputElement|null>(null)
  const load=async(next=path)=>{setError('');try{const listing=await apiFetch<Listing>('/api/v2/models?path='+encodeURIComponent(next));setPath(listing.path||'');setEntries(listing.entries||[]);const found=await apiFetch<{configs:string[]}>('/api/v2/models/configs');setConfigs(found.configs||[])}catch(e){setError(String(e))}}
  useEffect(()=>{void load('')},[]);useEffect(()=>{folderRef.current?.setAttribute('webkitdirectory','')},[])
  const create=async()=>{const name=window.prompt('New model folder name')?.trim();if(!name)return;setBusy(true);try{await apiFetch('/api/v2/models/directories',{method:'POST',body:JSON.stringify({path,name})});setMessage('Created '+name+'.');await load(path)}catch(e){setError(String(e))}finally{setBusy(false)}}
  const remove=async(entry:Entry)=>{if(!window.confirm('Delete '+entry.path+(entry.type==='directory'?' and all contents':'')+'?'))return;setBusy(true);try{await apiFetch('/api/v2/models?path='+encodeURIComponent(entry.path),{method:'DELETE'});setMessage('Deleted '+entry.path+'.');await load(path)}catch(e){setError(String(e))}finally{setBusy(false)}}
  const download=async(entry:Entry)=>{try{const blob=await apiBlob('/api/v2/models/download?path='+encodeURIComponent(entry.path));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=entry.name;a.click();URL.revokeObjectURL(url)}catch(e){setError(String(e))}}
  const extract=async(file:File,overwrite:boolean)=>{const form=new FormData();form.append('path',path);form.append('overwrite',String(overwrite));form.append('file',file);await apiFetch('/api/v2/models/extract',{method:'POST',body:form})}
  const upload=async(list:FileList|null,directory:boolean)=>{if(!list?.length)return;const files=Array.from(list) as DirectoryFile[];setBusy(true);setError('');setMessage('');try{if(directory){const form=new FormData();form.append('path',path);form.append('overwrite','false');files.forEach(file=>{form.append('files',file);form.append('relative_paths',file.webkitRelativePath||file.name)});await apiFetch('/api/v2/models/files',{method:'POST',body:form})}else{const archives=files.filter(file=>file.name.toLowerCase().endsWith('.zip'));const regular=files.filter(file=>!file.name.toLowerCase().endsWith('.zip'));const names=new Set(entries.map(entry=>entry.name));const conflicts=[...archives.map(file=>file.name.replace(/\.zip$/i,'')),...regular.map(file=>file.name)].filter(name=>names.has(name));const overwrite=conflicts.length?window.confirm('Replace existing model content?\n\n'+[...new Set(conflicts)].join('\n')):false;if(conflicts.length&&!overwrite)return;for(const file of archives)await extract(file,overwrite);if(regular.length){const form=new FormData();form.append('path',path);form.append('overwrite',String(overwrite));regular.forEach(file=>{form.append('files',file);form.append('relative_paths',file.name)});await apiFetch('/api/v2/models/files',{method:'POST',body:form})}}setMessage(String(files.length)+' model item'+(files.length===1?'':'s')+' uploaded.');await load(path)}catch(e){setError(String(e))}finally{setBusy(false);if(filesRef.current)filesRef.current.value='';if(folderRef.current)folderRef.current.value=''}}
  return <><div className="page-header"><div><div className="kicker">Configuration · model lifecycle</div><h1>Model library</h1></div><div className="header-actions">{isAdmin&&<><button className="btn" disabled={busy} onClick={()=>void create()}>New folder</button><button className="btn" disabled={busy} onClick={()=>filesRef.current?.click()}>Upload files</button><button className="btn btn-primary" disabled={busy} onClick={()=>folderRef.current?.click()}>Upload folder</button><input ref={filesRef} hidden type="file" multiple onChange={e=>void upload(e.target.files,false)}/><input ref={folderRef} hidden type="file" multiple onChange={e=>void upload(e.target.files,true)}/></>}</div></div>{message&&<div className="notice-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="model-library-grid"><section className="panel"><div className="panel-title"><div><h2>Shared models PVC</h2><p>Operator-managed model assets shared with inference services.</p></div><button className="btn" onClick={()=>void load(path)}>Refresh</button></div><div className="model-breadcrumbs"><button className="text-button" onClick={()=>void load('')}>/models</button>{path&&<span> / {path}</span>}</div>{path&&<button className="btn model-up-button" onClick={()=>void load(parent(path))}>← Parent folder</button>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Size</th><th>Actions</th></tr></thead><tbody>{entries.map(entry=><tr key={entry.path}><td>{entry.type==='directory'?<button className="text-button" onClick={()=>void load(entry.path)}>▸ {entry.name}</button>:<b>{entry.name}</b>}</td><td>{entry.type}</td><td>{size(entry.size)}</td><td><div className="model-row-actions"><button className="text-button" onClick={()=>void navigator.clipboard.writeText('/models/'+entry.path)}>Copy path</button>{entry.type==='file'&&<button className="text-button" onClick={()=>void download(entry)}>Download</button>}{isAdmin&&<button className="text-button danger-text" onClick={()=>void remove(entry)}>Delete</button>}</div></td></tr>)}</tbody></table>{!entries.length&&<div className="table-empty">This model directory is empty.</div>}</div></section><aside className="panel"><div className="panel-title"><div><h2>Pipeline model configs</h2><p>Discovered from the shared <code>models/model_configs</code> directory.</p></div></div><div className="scene-list">{configs.map(config=><div className="scene-row" key={config}><div><b>{config}</b><span>Available to camera pipelines</span></div></div>)}{!configs.length&&<div className="table-empty">No model config JSON files found.</div>}</div></aside></div></>
}
